# Generated by Django 3.0.4 on 2020-03-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20200326_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher', to='restapi.Teacher'),
        ),
    ]
