# Generated by Django 3.0.4 on 2020-03-30 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20200327_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='rate',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('rate', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Teacher')),
            ],
        ),
    ]
