# Generated by Django 3.0.4 on 2020-05-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
