# Generated by Django 3.0.4 on 2020-05-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0016_delete_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
