# Generated by Django 3.0.4 on 2020-05-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0018_answer_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
