# Generated by Django 3.0.6 on 2020-05-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0021_answer_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rate',
        ),
        migrations.AddField(
            model_name='answer',
            name='rate',
            field=models.ManyToManyField(to='restapi.Rate'),
        ),
    ]
