# Generated by Django 3.0.6 on 2020-05-18 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0022_auto_20200518_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rate',
        ),
        migrations.AddField(
            model_name='answer',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.Rate'),
        ),
    ]
