# Generated by Django 3.0.6 on 2020-05-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0023_auto_20200518_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rate',
        ),
    ]
