# Generated by Django 3.0.6 on 2020-05-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0024_remove_answer_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
