# Generated by Django 3.0.6 on 2020-05-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0025_delete_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
