# Generated by Django 3.0.6 on 2020-05-20 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0026_answer_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
