# Generated by Django 3.0.6 on 2020-05-22 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0027_auto_20200520_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 15, 18, 40, 223171, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 15, 18, 40, 221462, tzinfo=utc)),
        ),
    ]
