# Generated by Django 3.0.6 on 2020-05-22 15:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0028_auto_20200522_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 15, 21, 34, 579541, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='rate',
        ),
        migrations.AddField(
            model_name='answer',
            name='rate',
            field=models.ManyToManyField(to='restapi.Rate'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 15, 21, 34, 575889, tzinfo=utc)),
        ),
    ]
