# Generated by Django 3.0.6 on 2020-05-27 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0030_auto_20200525_0719'),
        ('restapi', '0030_auto_20200522_1539'),
    ]

    operations = [
    ]
