# Generated by Django 3.0.6 on 2020-05-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0032_auto_20200527_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
