# Generated by Django 3.1.1 on 2020-09-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0034_comment_studenttokenmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenttokenmodel',
            options={'verbose_name': 'Student Token', 'verbose_name_plural': 'Student Tokens'},
        ),
    ]
