# Generated by Django 3.1.1 on 2020-09-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0035_auto_20200920_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttokenmodel',
            name='key',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Key'),
        ),
    ]
