# Generated by Django 3.1.1 on 2020-09-20 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0037_auto_20200920_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttokenmodel',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='restapi.student', verbose_name='Student'),
        ),
    ]
