# Generated by Django 3.1.1 on 2020-09-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0038_auto_20200920_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(related_name='subjects', to='restapi.Subject'),
        ),
    ]
